### ISSUE TITLE
Crash on world build

### ISSUE THREAD

**Issue by Zygus42** [desagas/Biome-Id-Fixer#3] opened 2021-01-23 13:52 UTC
Possibly to do with using TerraForged as the world builder ?

[crash-2021-01-23_21.45.35-server.txt](https://github.com/desagas/Biome-Id-Fixer/files/5860291/crash-2021-01-23_21.45.35-server.txt)

biomeidfixer-1.16.4-1.0.0.s0

**Comment by drakray** [comment] 2021-01-23 15:31
Got the same error, no TerraForged though
https://pastebin.com/arqQwThW

**Comment by desagas** [comment] 2021-01-23 20:12
Duplicate of https://github.com/desagas/Biome-Id-Fixer/issues/2.

**Closed by desagas** 2021-01-23 20:12 UTC
