### ISSUE TITLE
i cant help me (server with odd end generation)

### ISSUE THREAD

**Issue by SugarDaddii** [desagas/Biome-Id-Fixer#1] opened 2021-01-21 01:33 UTC
https://imgur.com/a/l9Ccls7

can you help me what iam doing wrong?

**Comment by desagas** [comment] 2021-01-21 01:52
Questions:

1. What pack are you playing on?
1. And please, go to where the end is generating like that, and press F3, and in the middle lefthand side, you should see biome. It will be in this format: (minecraft:ice_spikes).
1. This honestly looks like an intentional biome. This mod does not change the registered biome ids, so, there are two things happening if that biome is not meant to be there:
    1. This is newly explored chunks, which, you being in the end, is highly likely, which means new biomes will now show up. BYG added a few new biomes recently, this may be one. Is this new chunks?
    1. You did not install this mod on the last version of the pack, and then copy over as described in the wiki? Did you install it as described? [How to Install on Current Packs](https://github.com/desagas/Biome-Id-Fixer/wiki/How-to-Install-on-Existing-Packs).

**Comment by desagas** [comment] 2021-01-21 01:54
I know BYG added a nether biome that looks like that ... which is beautiful, I would not be surprised if there is an end one, similar. The reason I think it is an intentional biome, is because the islands still generated AS IS, and not in the fashion of a full cave (nether) biome or overworld biome with sky and solid land.

**Comment by SugarDaddii** [comment] 2021-01-21 02:14
first it was alps biom all over the end with mineshafts all over the place i reset end completly only the first island where we fight the dragon!

When i download the world to my singleplayer world the energetice expansion biomes will load normally all over the place!
only on my server ( custom creation no modpack) i delete the old chunk and always try to generate new chunk but always there ar spawning these chunks of gravel_beaches with rain and mobs like creeper or skeleton!

iam so lost

**Comment by desagas** [comment] 2021-01-21 02:17
I can not help you unless you answer the questions I asked. Please, answer the questions, and then I can see what I can do.

**Comment by SugarDaddii** [comment] 2021-01-21 02:22
1. my own pack! 
2.Biome: biomesoplenty:gravel_beach
3.i have no last version because it my own modpack for friends

**Comment by desagas** [comment] 2021-01-21 02:25
Please upload the BiomeIdFix(doNOTedit).json file to a pastebin, and then share the link to it here.

**Comment by SugarDaddii** [comment] 2021-01-21 02:28
https://pastebin.com/LVrJQz8P

normally it should look like this
 
https://imgur.com/a/0pKgd2N ( tested on singleplayer world)
https://imgur.com/a/l9Ccls7 ( this is how it looks on my MultiplayerServer :D )

**Comment by SugarDaddii** [comment] 2021-01-21 02:52
and this is when i install your mod on my client than the ID are a bit different!

https://pastebin.com/Hi7bfUeX

**Comment by desagas** [comment] 2021-01-21 03:01
Okay, my end is fine ... so, I know why yours is like this ... 

###### If you read the information on the wiki for this mod, it explains how to install on existing packs, and gives warnings about stuff like this.

### I can recreate this (but it has nothing to do with my mod):
1. You created a pack, and made a server of it. It is your pack.
1. You started playing the server world.
1. Over time, you updated added or removed different mods, here and there. Chances are, you updated BoP at one point, or removed a mod, and added ratlantis, etc.
1. In your server, you played, loaded the world, loaded some end places, etc.
1. This causes Vanillia Forge/Minecraft to reshift the biome ids, which means NEW generation will not match the biomes of the old generation, necessarily.
1. You say it was "alps?" That means that part of the end was loaded previously under a different biome id, which means some mod you installed, updated, or removed contained a biome, which caused a shift. Because vanilla currently sees that biome as alps, it would rain and show, etc.
1. I know without a doubt in my mind that this is exising generation: how, because as I said above, if it was new generation, it would have land mass like the overworld does.

###### Minecraft saves biome numerical ids, NOT biome names or information, so when they shifted, an old end biome id was likely remapped with the current alps biome (for example, end biome used to be id 41, but is now 63, where alps is now 41, which means vanilla/forge is making the biome act like the apls).

But, I am still going to try and help you.

#### If you were to install this mod on both Client AND Server, and delete the end, when reloaded, they both should be identical.
* Can you back up your server, and then delete the Dim 1 folder from your World folder.
* Can you then verify that mods on the server and your client are IDENTICAL.
* Can you then please load your Server, and visit the end, in this exact place you showed above.
* Lastly, please share both BiomeIdFix(doNOTedit).json files with me, from your machine and your server.

**Comment by SugarDaddii** [comment] 2021-01-21 03:24
i say it bop:gravel_beach now .... alps it was before i installed your mod!

okay first thing i was seeing that the endframe (no portal back to overworld) is completly lost :D and also the gateways to outer End arnt there any more!

This is the place:
https://imgur.com/a/wsoOxzW /Nothing changed/

https://pastebin.com/A39Lr7N2 ---->/Server/

https://pastebin.com/YsKLQjV0 ----->/Client/

**Comment by desagas** [comment] 2021-01-21 03:31
Okay, give me a bit, I can see that a mod called Endergetic is inserting a biome randomly into the mix, shift all the ids. Let me see what I can do.

**Comment by SugarDaddii** [comment] 2021-01-21 03:33
i should copy the BiomeIdFix(doNOTedit).json from client to server?

**Comment by desagas** [comment] 2021-01-21 03:34
No, from Server to client. As your server is already loaded and active.

**Comment by SugarDaddii** [comment] 2021-01-21 03:38
but when i do this nothing will change on the generation on my server ... because the energetic expansion is the biome what should generate in the end because it is a end addon!

**Comment by desagas** [comment] 2021-01-21 03:41
It should work fine on your server. I do not change how minecraft handles the biomes. Regardless of what biome ID it has, if it is assigned to the end dimension, it will generate in the end dimension.

**Comment by SugarDaddii** [comment] 2021-01-21 03:46
https://imgur.com/a/p5iYjz7 
i never see that a gravel_beach is generated in the end! 
https://imgur.com/a/H9jtlv6
i also dont see mineshaft so often in end XD

there is something rly strange!

**Comment by desagas** [comment] 2021-01-21 03:49
Did you copy the JSON from your SERVER and put it in your Client? NOT in the world folder, in the MAIN directoty?

**Comment by desagas** [comment] 2021-01-21 03:50
What version of my mod are you using?

**Comment by SugarDaddii** [comment] 2021-01-21 03:50
https://imgur.com/a/r1aKUxg

there it is

**Comment by SugarDaddii** [comment] 2021-01-21 03:53
iam a bit scared if iam generating a gravel_beach in the overworld that it will be and end biome now

**Comment by desagas** [comment] 2021-01-21 03:56
Yeah, as I said, this mod does not change the way it generates.

**Comment by SugarDaddii** [comment] 2021-01-21 03:58
so iam fked now :P because i cant get the generation to work like it should be? but there must be a solution !

**Comment by desagas** [comment] 2021-01-21 03:58
I see you created another issue as well on their issues page? Was this before or after installing my mod?

**Comment by SugarDaddii** [comment] 2021-01-21 03:59
before!

**Comment by desagas** [comment] 2021-01-21 04:07
This mod DOES NOT change the way biomes generate, nor where they generate.

Lets think logically for a moment:
If you look at your end, Is that a gravel beach? Like, don't read what the biome is called, literally look at it ... is that a gravel beach? Clearly it is not, on both server and single player worlds you have shown me.

So ... please tell me if any of the following is incorrect:
1. The island is in the exact same space before and after installing my mod, new world and old world.
    1. Is this accurate?
1. The island's biome was called gravel beach before and after installing my mod.
    1. Is this accurate?

**Comment by SugarDaddii** [comment] 2021-01-21 04:15
So maybe iam not clearly!

First i encountered the problem was when we first enter the end! 
Where the Biome of the Mod : endergetic should be was the Alps Biome of BOP! 

Than i downloaded the World Folder to my Client and start a Singleplayer with the saves of my Multiplayerserverfiles i downloaded your Mod remove all region files and generated the end new!

After i was doing so All Biomes work like they should! 
https://imgur.com/a/0pKgd2N ----->/Client/Singleplayer World This was fine

So i was trying to fix it the same way on my server files!
and it wasnt working the same way as in my singleplayer world!

**Comment by desagas** [comment] 2021-01-21 05:09
As long as your JSON files match IDENTICALLY for my MOD, on both the SERVER and your CLIENT, NEW biomes will match, already generated biomes will not. As I have said here, in my Wiki, and on the Mod page, Biome Id Fixer does not regenerate chunks which have already been generated. You need to look very closely, they may look identical, as it is very easy to miss even the smallest changes, that is way I say copy and paste, NOT simply leave it be. In the two files you showed me above, endergetic was registered as 51 on your Server and as 135 on your client. This means that EVERY non minecraft biome between 51 and 135 was shifted. This is not a result of my mod, this is a result of not copying and pasting, as suggested, and not making sure the JSONS are identical. My mod does not erase what biomes are already saved to that JSON, it simply adds new biomes to it when they are added to the game.

You do not want to copy the JSON from your client TO your server, because they all your other biomes between 51 and 135 will be messed up everywhere else, at least for currently generated chunks.

To fix the end generation, I would recommend deleting your Dim 1(end dimension) from your world folder ON YOUR SERVER, AFTER making sure that both BiomeIdFixer JSON files are identical on your CLIENT and SERVER (copy FROM SERVER and paste TO CLIENT before loading your Client from startup (not the world, the actual machine that runs Minecraft).

This is the only solution I have for you, as it is not an issue related to my mod, and is out of its scope. My mod does not control when biomes are registered, and since Endergetic is seemingly registering the biome at different times on both Client and Server, I have no control over that with my mod.

If on your server, that biome is associated with biome id 51, it will load into minecraft with biome id 51, and it will tell your client that biome 51 is loaded, not that that biome name is loaded. Therefore, the server will show the name of the servers biome 51, as well as generate with biome 51 generation, but your client will tell you that the clients biome 51 exists there, in your case, the gravel beach.

Also, I would take a moment to make sure that BoP, RatsAtlantis and Endergenic are the exact same version on both your Server and your Client. If they are not identical on both sides, this could cause a major dsync as well.

So, I am forced to say that my mod is working as intended, in this case.

I will, however, work with this a bit over the next few days, and see if there is anything I can do to make sure other mods like endergenic are registered in order every time, but it is not the intended purpose of my mod.

Ref: https://github.com/team-abnormals/endergetic/issues/141

**Comment by SugarDaddii** [comment] 2021-01-21 05:36
So iam thing i got it!

1. deinstall energetic expansion mod
2. delte Dim1
3. load world without mod
4. load dim1
5. use BiomeFixer
6. stop server
7. install mod
8. BiomeFixer gives mod a new ID
9. go to End ----> Fixed

**Comment by desagas** [comment] 2021-01-21 05:40
Fast, I know, but update. I have tested the combination of mods that add biomes in your pack, on Windows PC, and MacOS, both server and client versions, and with ten tests each, every single time, the biomes register in the exact same order, with endergetic getting biomeID 51, without exception.

I believe you may have misread some instructions on how to use the mod, or there is another mod in your pack that is causing mods to register in random sequence.

There is currently an issue on Endergetics github that talks about biomes showing up in the wrong dimensions. This may be related. If you had alps spawn in the end, you need to follow up on that issue.

**Closed by desagas** 2021-01-21 05:40 UTC
Labels: further investigation needed, invalid, out of scope, user error

**Comment by SugarDaddii** [comment] 2021-01-21 16:26
i want to thx you for your patient yesterday! 
i love how you try to help me it was very nicly done by you!

have a wondeful day

**Comment by desagas** [comment] 2021-01-21 19:44
I am happy that you were able to get it to work. I knew it was because you added a mod after installing my mod. When using Biome Id Fixer, both client and server must do the exact same thing, to get the exact same biome id results.
